[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "twardown-py"
version = "0.1.0"
description = "Python plugin for the Python Markdown ecosystem that provides an opinionated Markdown flavor"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Adam Twardoch", email = "adam@twardoch.com" },
]

[project.urls]
Homepage = "https://github.com/twardoch/twardown-py"
Repository = "https://github.com/twardoch/twardown-py.git"

[tool.hatch.build.targets.wheel]
packages = ["src/twardown-py"]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
